### ISSUE TITLE
TypeError: compile() missing 1 required positional argument: 'loss'

### ISSUE THREAD

**Issue by kaustubholpadkar** [llSourcell/autoencoder_explained#1]
When I tried to run the code, I face this error on given line.
![error](https://user-images.githubusercontent.com/15917698/35472614-40c3e66c-0398-11e8-8a62-1a186d965e1c.png)

-> vae.compile(optimizer='rmsprop')
TypeError: compile() missing 1 required positional argument: 'loss'

**Comment by 3zuli** [comment]
This seems to work for me:
`vae.compile(optimizer='rmsprop', loss='')`

**Comment by dsadulla** [comment]
Try this:

```
vae.add_loss(vae_loss)
vae.compile(optimizer = 'rmsprop', loss = None)
vae.summary()
```

Check May4m's reply [here](https://github.com/keras-team/keras/commit/10b46cbdc47f7164cd92209077939a7f7882b3c0#commitcomment-27165166) regarding this. It worked for me

@3zuli  's answer is also valid.
